apiVersion: apps/v1
kind: Deployment
metadata:
  name: struts-cli-demo
  labels:
    app: struts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: struts
  template:
    metadata:
      labels:
        app: struts
    spec:
      containers:
      - name: struts
        image: skywalke34/struts
        ports:
        - containerPort: 8080
          name: 8080tcp8080
          protocol: TCP

