apiVersion: apps/v1
kind: Deployment
metadata:
  name: dply-struts-cli-demo
  labels:
    app: struts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: struts
  template:
    metadata:
      labels:
        app: struts
    spec:
      containers:
      - name: struts
        image: skywalke34/struts
        ports:
        - containerPort: 8080
          name: 8080tcp8080
          protocol: TCP

apiVersion: v1
kind: Service
metadata:
  name: svc-struts-cli-demo
spec:
  selector:
    app.kubernetes.io/name: struts-cli-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080tcp8080
      nodePort: 28080
      
